### ISSUE TITLE
Uncaught (in promise) Error: No PrimeVue Toast provided!

### ISSUE THREAD

**Issue by MiljanStojanovic93** [SnowdogApps/a11y-audit-tool#10]
Expected behaviour
Create project successfully

Actual behaviour
usetoast.esm.js?v=baebeb8e:7 Uncaught (in promise) Error: No PrimeVue Toast provided!
    at useToast (usetoast.esm.js?v=baebeb8e:7:11)
    at handleError (error.ts:27:25)
    at CreateProjectForm.vue:59:5

Steps to reproduce
Try to create new project in /admin page

Environment
System:
OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
Memory: 7.69 GB / 31.27 GB
Shell: 5.2.15 - /bin/bash
Binaries:
Node: 18.19.0 - /usr/bin/node
npm: 9.2.0 - /usr/bin/npm

**Comment by MiljanStojanovic93** [comment]
My fault guys, i did not create tables in supabase by running scripts provided in sql folder. Now it is working flawlessly for manual testing.
